Ban17 product find all changed products
OleksiyKharkiv/GutBank pull request #2
Opened 2023-03-15 18:11 UTC by OleksiyKharkiv

2023-03-23 14:36 UTC, kentaskis reviewed
alles ist gut

2023-03-28 15:09 UTC, kentaskis commented on src/test/java/com/example/gutbank/controller/ProductControllerTest.java
> +
мне кажеться здесь должно быть продолжение, т.е. ты замокал сервис, но функцию так и не вызвал

2023-04-07 16:28 UTC, RomanRichert requested changes

2023-04-07 16:28 UTC, RomanRichert commented on src/main/java/com/example/gutbank/controller/ProductController.java
> +public class ProductController {
строка

2023-04-07 16:28 UTC, RomanRichert commented on src/main/java/com/example/gutbank/dto/ProductDto.java
> +public class ProductDto {
строка. и между полями пустые строки тоже

2023-04-07 16:28 UTC, RomanRichert commented on src/test/java/com/example/gutbank/util/DtoCreator.java
> +                getManagerDTO()
Тесты не работают, ошибка тут

2023-04-07 16:28 UTC, RomanRichert commented on src/test/java/com/example/gutbank/service/ProductServiceImplTest.java
> +    private ProductRepository productRepository;
строка

2023-04-07 16:28 UTC, RomanRichert commented on src/test/java/com/example/gutbank/service/ProductServiceImplTest.java
> +
@InjectMocks и можешь убрать 37 строчку

2023-04-07 16:28 UTC, RomanRichert commented on src/test/java/com/example/gutbank/service/ProductServiceImplTest.java
> +        Product product1 = new Product(1, null, "Product 1", ProductStatus.ACTIVE, Currencies.USD, BigDecimal.valueOf(2.5), 1000, Timestamp.valueOf(LocalDateTime.now().minusHours(1)), Timestamp.value
Для чего тебе тогда EntityCreator, если ты тут их создаёшь?

2023-04-07 16:28 UTC, RomanRichert commented on src/test/java/com/example/gutbank/mapper/ProductMapperTestGPT.java
> +        assertEquals("1", productDto.getId());
Опять, зачем тебе тогда EntityCreator, если ты тут сравниваешь каждое поле отдельно и создаёшь тут сущности? лучше сравнивать один объект с другим, чем отдельно каждое из его полей.

2023-04-07 16:28 UTC, RomanRichert commented on src/test/java/com/example/gutbank/mapper/ProductMapperTest.java
> +        Product product = EntityCreator.getProduct();
аналогично

2023-04-07 16:28 UTC, RomanRichert commented on src/main/java/com/example/gutbank/dto/ManagerDto.java
> +public class ManagerDto {
Где пустые  строки между полями?

2023-04-07 16:28 UTC, RomanRichert commented on src/main/java/com/example/gutbank/dto/ManagerDto.java
> +import java.sql.Timestamp;
строка

2023-04-07 16:28 UTC, RomanRichert commented on src/main/java/com/example/gutbank/entity/Account.java
>      @Id
комментарии то удали

2023-04-07 16:28 UTC, RomanRichert commented on src/main/java/com/example/gutbank/mapper/ProductMapper.java
> +    ProductDto toDto(Product product);
пустые строки...

2023-04-07 16:28 UTC, RomanRichert commented on src/main/java/com/example/gutbank/repository/ProductRepository.java
> +public interface ProductRepository extends CrudRepository<Product, Integer> {
нужна пустая строка

2023-04-07 16:28 UTC, RomanRichert commented on src/main/java/com/example/gutbank/repository/ProductRepository.java
> +
а тут они не нужны

2023-04-07 16:28 UTC, RomanRichert commented on src/main/java/com/example/gutbank/service/ProductService.java
> +    List<Product>findAll();
строки

2023-04-14 19:04 UTC, merged